unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Error, FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def,
  FireDAC.Stan.Pool, FireDAC.Stan.Async, FireDAC.Phys, FireDAC.Phys.FB,
   FireDAC.Phys.FBDef, FireDAC.VCLUI.Wait,FireDAC.DApt,
  Data.DB, FireDAC.Comp.Client,MegaMigrator,
  Vcl.StdCtrls, Sql.Builder, ClipBrd,Sql.Script.Builder, Vcl.ExtCtrls;

type
  TForm1 = class(TForm)
    FDConnection1: TFDConnection;
    Memo1: TMemo;
    Panel1: TPanel;
    Button3: TButton;
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
  private
    MegaMigrator : TMegaMigration;
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.Button1Click(Sender: TObject);

begin
  FDConnection1.Open();
  MegaMigrator := TMegaMigration.Create(self, FDConnection1);
  Memo1.Lines.Text :=  MegaMigrator.GenerateScript;
  ShowMessage('Concluido');
end;

procedure TForm1.Button3Click(Sender: TObject);
var
 script : TScriptBuilder;
begin
  script := TScriptBuilder.Create;
  script.Append(
  '/******************************************************************************/'+slineBreak+
  '/****              Generated by IBExpert 07/05/2025 22:54:05               ****/'+slineBreak+
  '/******************************************************************************/'+slineBreak+
  '                                                                                '+slineBreak+
  '/******************************************************************************/'+slineBreak+
  '/****     Following SET SQL DIALECT is just for the Database Comparer      ****/'+slineBreak+
  '/******************************************************************************/');


//  script.NewSQL.AppendLine('CREATE TABLE NOME (')
//                  .IncIndent
//                  .AppendLine('teste')
//                  .DecIndent
//                  .AppendLine(');');







  script.AppendLine('--End Script');

  Memo1.Lines.Text := script.AsString;
end;

end.
