SELECT
   FIELD_NAME,
   FIELD_TYPE,
   FIELD_NULL,
   FIELD_CHARSET,
   FIELD_COLLATION,
   FIELD_DEFAULT,

   TRIM(
    FIELD_DEFAULT||
    IIF(COALESCE(FIELD_NULL,'') = '','',' '||FIELD_NULL)||
    IIF(COALESCE(FIELD_CHARSET,'') IN ('NONE',''),'',' '||FIELD_CHARSET)||
    IIF(COALESCE(FIELD_COLLATION,'') IN ('NONE',''),'',' '||FIELD_COLLATION)
   )  AS FIELD_SET

FROM (

 SELECT
   TRIM(RF.RDB$FIELD_NAME) FIELD_NAME,
   TRIM(RF.rdb$relation_name) RELATION_NAME,
   F.rdb$segment_length SEGMENT_LENGTH,
   CASE F.RDB$FIELD_TYPE
     WHEN 7 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'SMALLINT'
         WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 8 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'INTEGER'
         WHEN 1 THEN 'NUMERIC('  || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 9 THEN 'QUAD'
     WHEN 10 THEN 'FLOAT'
     WHEN 12 THEN 'DATE'
     WHEN 13 THEN 'TIME'
     WHEN 14 THEN 'CHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
     WHEN 16 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'BIGINT'
         WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 23 THEN 'BOOLEAN'
     WHEN 27 THEN 'DOUBLE'
     WHEN 35 THEN 'TIMESTAMP'
    WHEN 37 THEN 'VARCHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / COALESCE(CH.RDB$BYTES_PER_CHARACTER,1))) || ')'
     WHEN 40 THEN 'CSTRING' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
     WHEN 45 THEN 'BLOB_ID'
     WHEN 261 THEN 'BLOB SUB_TYPE ' || TRIM(IIF(F.RDB$FIELD_SUB_TYPE = 0,'BINARY','TEXT')||' SEGMENT SIZE '||COALESCE(F.rdb$segment_length,80))
     ELSE 'RDB$FIELD_TYPE: ' || F.RDB$FIELD_TYPE || '?'
   END AS FIELD_TYPE,
   IIF(COALESCE(RF.RDB$NULL_FLAG, 0) = 0, '', 'NOT NULL') FIELD_NULL,
   CH.RDB$CHARACTER_SET_NAME FIELD_CHARSET,
   DCO.RDB$COLLATION_NAME FIELD_COLLATION,
   TRIM(COALESCE(RF.RDB$DEFAULT_SOURCE, F.RDB$DEFAULT_SOURCE, '')) FIELD_DEFAULT,
   F.RDB$VALIDATION_SOURCE FIELD_CHECK,
   RF.RDB$DESCRIPTION FIELD_DESCRIPTION
 FROM RDB$RELATION_FIELDS RF
 JOIN RDB$FIELDS F ON (F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE)
 LEFT JOIN RDB$CHARACTER_SETS CH ON (CH.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID)
 LEFT JOIN RDB$COLLATIONS DCO ON ((DCO.RDB$COLLATION_ID = F.RDB$COLLATION_ID) AND (DCO.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID))
 WHERE  (COALESCE(RF.RDB$SYSTEM_FLAG, 0) = 0)
  and rf.rdb$view_context is null
   and rf.rdb$relation_name = :table_name
 ORDER BY RF.RDB$FIELD_POSITION
)
