SELECT
  RC.RDB$CONSTRAINT_NAME AS FK_NAME,
  RC.rdb$index_name AS INDEX_NAME,
  RC.RDB$RELATION_NAME AS TABLE_NAME,
  SG.RDB$FIELD_NAME AS FIELD_NAME,
  RCREF.rdb$relation_name AS REF_TABLE_NAME,
  RSG.RDB$FIELD_NAME AS REF_FIELD_NAME
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$REF_CONSTRAINTS REF ON REF.RDB$CONSTRAINT_NAME = RC.RDB$CONSTRAINT_NAME
JOIN RDB$RELATION_CONSTRAINTS RCREF ON RCREF.RDB$CONSTRAINT_NAME = REF.RDB$CONST_NAME_UQ
JOIN RDB$INDEX_SEGMENTS SG ON SG.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
JOIN RDB$INDEX_SEGMENTS RSG ON RSG.RDB$INDEX_NAME = RCREF.RDB$INDEX_NAME
WHERE RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
  AND RC.RDB$RELATION_NAME = :TABLE_NAME
