
SELECT
  TRIM(I.RDB$INDEX_NAME) AS INDEX_NAME,
  ( SELECT LIST(TRIM(S.RDB$FIELD_NAME),', ') FROM RDB$INDEX_SEGMENTS S
    WHERE S.rdb$index_name = I.RDB$INDEX_NAME
   ) AS FIELDS,
  I.RDB$EXPRESSION_SOURCE AS EXPRESSION,
  CASE I.rdb$unique_flag WHEN 1 THEN 'S' ELSE 'N' END AS IS_UNIQUE,
  CASE I.RDB$INDEX_INACTIVE WHEN 0 THEN 'S' ELSE 'N' END AS IS_ACTIVE,
  IIF(coalesce(i.rdb$index_type,0) = 1,'DESCENDING','ASCENDING' ) AS SORTING
FROM RDB$INDICES I
LEFT JOIN RDB$RELATION_CONSTRAINTS C ON C.RDB$INDEX_NAME = I.RDB$INDEX_NAME
WHERE I.RDB$RELATION_NAME = :TABLE_NAME
  AND C.RDB$INDEX_NAME IS NULL
ORDER BY I.rdb$index_name


