SELECT
  TRIM(RC.RDB$CONSTRAINT_NAME) AS UNIQUE_NAME,
  TRIM(RC.RDB$INDEX_NAME) AS INDEX_NAME,
  LIST(TRIM(SI.RDB$FIELD_NAME)) AS FIELDS_NAME,
  MAX(iif(coalesce(i.rdb$index_type,0) = 1,'DESCENDING','ASCENDING' )) AS SORTING
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$INDEX_SEGMENTS SI ON SI.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
JOIN RDB$INDICES I ON TRIM(I.rdb$index_name) = TRIM(RC.RDB$INDEX_NAME)
WHERE RC.RDB$CONSTRAINT_TYPE = 'UNIQUE'
  AND RC.RDB$RELATION_NAME = :TABLE_NAME
  GROUP BY 1,2

