 SELECT
  TRIM(RC.RDB$CONSTRAINT_NAME) AS CHECK_NAME,
  TRIM(T.RDB$TRIGGER_SOURCE) AS CHECK_SOURCE
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$CHECK_CONSTRAINTS CC ON CC.RDB$CONSTRAINT_NAME = RC.RDB$CONSTRAINT_NAME
JOIN RDB$TRIGGERS T ON T.RDB$TRIGGER_NAME = CC.RDB$TRIGGER_NAME
WHERE RC.RDB$CONSTRAINT_TYPE = 'CHECK'
  AND RC.RDB$RELATION_NAME = :TABLE_NAME
 GROUP BY 1,2