SELECT
   FIELD_NAME,
   FIELD_TYPE,
   FIELD_NULL,
   FIELD_CHARSET,
   FIELD_COLLATION,
   FIELD_DEFAULT,
   "POSITION",
   PARAMETER_DIRECTION,
   TRIM(
    FIELD_DEFAULT||
    IIF(COALESCE(FIELD_NULL,'') = '','',' '||FIELD_NULL)||
    IIF(COALESCE(FIELD_CHARSET,'') IN ('NONE',''),'',' '||FIELD_CHARSET)||
    IIF(COALESCE(FIELD_COLLATION,'') IN ('NONE',''),'',' '||FIELD_COLLATION)
   )  AS FIELD_SET
FROM
(

SELECT
  TRIM(p.RDB$PROCEDURE_NAME) AS PROCEDURE_NAME,
  TRIM(p.RDB$PARAMETER_NAME) AS FIELD_NAME,


   CASE F.RDB$FIELD_TYPE
     WHEN 7 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'SMALLINT'
         WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 8 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'INTEGER'
         WHEN 1 THEN 'NUMERIC('  || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 9 THEN 'QUAD'
     WHEN 10 THEN 'FLOAT'
     WHEN 12 THEN 'DATE'
     WHEN 13 THEN 'TIME'
     WHEN 14 THEN 'CHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
     WHEN 16 THEN
       CASE F.RDB$FIELD_SUB_TYPE
         WHEN 0 THEN 'BIGINT'
         WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ',' || (-F.RDB$FIELD_SCALE) || ')'
         WHEN 2 THEN 'DECIMAL'
       END
     WHEN 23 THEN 'BOOLEAN'
     WHEN 27 THEN 'DOUBLE'
     WHEN 35 THEN 'TIMESTAMP'
    WHEN 37 THEN 'VARCHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / COALESCE(CH.RDB$BYTES_PER_CHARACTER,1))) || ')'
     WHEN 40 THEN 'CSTRING' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
     WHEN 45 THEN 'BLOB_ID'
     WHEN 261 THEN 'BLOB SUB_TYPE ' || TRIM(IIF(F.RDB$FIELD_SUB_TYPE = 0,'BINARY','TEXT')||' SEGMENT SIZE '||COALESCE(F.rdb$segment_length,80))
     ELSE 'RDB$FIELD_TYPE: ' || F.RDB$FIELD_TYPE || '?'
   END AS FIELD_TYPE,
   CASE p.RDB$PARAMETER_TYPE
    WHEN 0 THEN 'INPUT'
    WHEN 1 THEN 'OUTPUT'
    ELSE 'UNKNOWN'
  END AS PARAMETER_DIRECTION,
  IIF(COALESCE(P.rdb$null_flag, 0) = 0, '', 'NOT NULL') FIELD_NULL,
  TRIM(COALESCE(P.rdb$default_source, F.RDB$DEFAULT_SOURCE, '')) FIELD_DEFAULT,
  f.RDB$FIELD_SUB_TYPE,
  f.RDB$FIELD_LENGTH,
  f.RDB$FIELD_PRECISION,
  f.RDB$FIELD_SCALE,
  TRIM(CH.RDB$CHARACTER_SET_NAME) AS FIELD_CHARSET,
  DCO.RDB$COLLATION_NAME FIELD_COLLATION,
  p.RDB$PARAMETER_NUMBER AS "POSITION"
FROM RDB$PROCEDURE_PARAMETERS p
LEFT JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME = p.RDB$FIELD_SOURCE
LEFT JOIN RDB$CHARACTER_SETS CH ON (CH.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID)
LEFT JOIN RDB$COLLATIONS DCO ON ((DCO.RDB$COLLATION_ID = F.RDB$COLLATION_ID) AND (DCO.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID))
WHERE TRIM(p.RDB$PROCEDURE_NAME) = :PROCEDURE_NAME
ORDER BY p.RDB$PROCEDURE_NAME, p.RDB$PARAMETER_TYPE, p.RDB$PARAMETER_NUMBER
)
