SELECT
  TRIM(RDB$TRIGGER_NAME) AS TRIGGER_NAME,
  RDB$RELATION_NAME AS TABLE_NAME,
  RDB$TRIGGER_SEQUENCE AS TRIGGER_POSITION,
  IIF(RDB$TRIGGER_INACTIVE = 0,'S','N') AS IS_ACTIVE,
  RDB$TRIGGER_TYPE as TRIGGER_TYPE,
   RDB$TRIGGER_SOURCE AS TRIGGER_SOURCE,
  IIF(UPPER(RDB$TRIGGER_SOURCE) LIKE '%GEN_ID%' or UPPER(RDB$TRIGGER_SOURCE) LIKE '%NEXT VALUE FOR%','S','N') AS IS_FOR_GENERATOR
FROM RDB$TRIGGERS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0
ORDER BY RDB$TRIGGER_SEQUENCE
