CREATE DESCENDING INDEX IDX_DESC ON TESTE_INDICES (TESTE);
CREATE UNIQUE DESCENDING INDEX IDX_DESC_UNIQUE ON TESTE_INDICES (EITA);
CREATE INDEX IDX_EXPRESSION ON TESTE_INDICES COMPUTED BY (UPPER(TESTE));
CREATE UNIQUE INDEX IDX_UNIQUE ON TESTE_INDICES (TESTE);
CREATE INDEX TESTE_INDICES_IDX1 ON TESTE_INDICES ("MAIS UMA");
