CREATE TABLE ABASTECIMENTO (
    ID_AB                       BIGINT,
    DATA                        DATE,
    HORA                        VARCHAR(10),
    BOMBA                       VARCHAR(10),
    BICO                        VARCHAR(10),
    TANQUE                      VARCHAR(10),
    REG_INICIO                  NUMERIC(15,4),
    REG_FINAL                   NUMERIC(15,4),
    CODIGO                      VARCHAR(14),
    LITRO                       NUMERIC(15,4),
    PRECO                       NUMERIC(15,4),
    TOTAL                       NUMERIC(15,4),
    CANAL                       VARCHAR(5),
    UNIDADE                     VARCHAR(4),
    POSICAO                     VARCHAR(10),
    REGISTRO                    VARCHAR(50),
    ENVIADO                     VARCHAR(1),
    STATUS                      VARCHAR(20),
    ID_SAIDA                    BIGINT,
    REGISTRO_ALTERADO           VARCHAR(1) DEFAULT 'N',
    SERIE_ECF                   VARCHAR(20),
    COO                         VARCHAR(6),
    FATURADO                    VARCHAR(1) DEFAULT 'N',
    NOTA_FISCAL                 VARCHAR(10),
    ESTOQUE_INICIAL             NUMERIC(15,5),
    TAG1                        VARCHAR(50),
    TAG2                        VARCHAR(50),
    ID_FRENTISTA                INTEGER DEFAULT 0,
    ID_CLIENTE                  INTEGER DEFAULT 0,
    JUSTIFICATIVA_AFERICAO      VARCHAR(255),
    DESCONTINUIDADE_ENCERRANTE  CHAR(1) DEFAULT 'N',
    DATA_HORA_SERVIDOR          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRECO_LIQUIDO               NUMERIC(15,4),
    SUBTOTAL_LIQUIDO            NUMERIC(15,4),
    VALOR_DESCONTO              NUMERIC(15,2),
    VALOR_ACRESCIMO             NUMERIC(15,2),
    PRECO_ESPECIAL              NUMERIC(15,4),
    BKP_TANQUE                  VARCHAR(10),
    BKP_BOMBA                   VARCHAR(10),
    BKP_BICO                    VARCHAR(10),
    BKP_REGINICIO               NUMERIC(15,4),
    BKP_REGFINAL                NUMERIC(15,4),
    BKP_STATUS                  VARCHAR(20),
    BKP_LITRO                   NUMERIC(15,4),
    ID_NFCE                     BIGINT,
    ID_ITEM_NFCE                BIGINT,
    COD_VIRGULA                 VARCHAR(5),
    BAIXOU_ESTOQUE              CHAR(1),
    RESERVADO_FATURAMENTO       CHAR(1),
    NUMERO_TURNO                INTEGER,
    HASH_TERMINAL               VARCHAR(50),
    VERSAO_INTEGRADOR           VARCHAR(50),
    ST_FULL                     VARCHAR(200)
);
